name: Health Check

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: https://full-stack-open-pokedex-jeme.herokuapp.com/health
          max-attempts: 3
          retry-delay: 10s