name: Health Check

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Health Check
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: https://full-stack-open-pokedex-jeme.herokuapp.com/health
          max-attempts: 3
          retry-delay: 10s
