name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "full-stack-open-pokedex-jeme"
          heroku_email: "eemelijoonatan@gmail.com"
          healthcheck: "https://full-stack-open-pokedex-jeme.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true